spring.application.name=EcommerceApi

# 1. Database Connection (Make sure you created 'ecommerce_db' in MySQL Workbench)
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Fixerr77

# 2. Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect